Pinned coverage package version to 4.1b2 in requirements.txt
Latest version of coverage package (4.1b3) changes reporter mechanism and
breaks coveralls reporter:

$ coveralls
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/Users/tcn/Develop/projects/odin/venv-2.7/bin/coveralls", line 11, in <module>
    sys.exit(main())
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/cli.py", line 62, in main
    result = coverallz.wear()
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/api.py", line 89, in wear
    json_string = self.create_report()
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/api.py", line 107, in create_report
    data = self.create_data()
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/api.py", line 156, in create_data
    self._data = {'source_files': self.get_coverage()}
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/api.py", line 174, in get_coverage
    return reporter.report()
  File "/Users/tcn/Develop/projects/odin/venv-2.7/lib/python2.7/site-packages/coveralls/reporter.py", line 29, in report
    units = self.code_units if hasattr(self, 'code_units') else self.file_reporters
AttributeError: 'CoverallReporter' object has no attribute 'file_reporters'